version: '2'
services:

  api:
    build: api/.
    ports:
      - "4000:5000"
    links:
      - mysql
    depends_on:
      - mysql

  mysql:
    build: mysql/.
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql
    environment:
       passwd: dockerfiap
       user: alunofiap
       database: trabalhofinalfiap
